export const ActionTypes = {
    ALL_PRODUCTS: "ALL_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "DELETE_PRODUCT",
  };